### ISSUE TITLE
Inspirational sites

### ISSUE THREAD

**Issue by njsfield** [GlobeTownDevs/blog#2]
Comment here with links & notable features

**Comment by tbtommyb** [comment]
I think [this site](http://www.creativebloq.com/portfolios/examples-712368) has some good ones, particularly [this](http://www.bleed.com/), [this](http://charlottetang.com/), [this](http://strange.wales/) and [this](http://www.hihayk.com/).

Obviously we are limited by the photos and graphics we have so I tried to choose fairly flat ones that aren't image intensive.

**Comment by njsfield** [comment]
this [site](http://www.tooplate.com/live/2075-digital-team) has a nice organised one page look, with sections to introduce the team and showcase a portfolio

**Comment by lucymonie** [comment]
Design inspiration/ideas:
https://wordpress.com/theme/venture
https://wordpress.com/theme/bailey
https://wordpress.com/theme/solar
https://blackrockdigital.github.io/startbootstrap-portfolio-item/
https://blackrockdigital.github.io/startbootstrap-agency/
https://blackrockdigital.github.io/startbootstrap-landing-page/
https://jenniferdewalt.com/
