### ISSUE TITLE
Get codewars icon

### ISSUE THREAD

**Issue by lucymonie** [GlobeTownDevs/blog#4]
[Codewars icon](https://cloud.githubusercontent.com/assets/2475572/4744687/6c8f7d32-5a32-11e4-97cd-0f430ec9788a.png)

**Comment by lucymonie** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/4809

**Comment by marisid** [comment]
Thanks Lucy but it doesn't work properly. I'm trying to figure out a way around it:)

**Comment by marisid** [comment]
Done, found an alternative at the end!
