### ISSUE TITLE
Linkedin icons floating around

### ISSUE THREAD

**Issue by emilyb7** [GlobeTownDevs/blog#67]
<img width="845" alt="screen shot 2016-10-21 at 10 55 58" src="https://cloud.githubusercontent.com/assets/17532458/19594456/063b1b24-977d-11e6-8081-2c2d476a64b1.png">
<img width="690" alt="screen shot 2016-10-21 at 10 56 45" src="https://cloud.githubusercontent.com/assets/17532458/19594474/18ec369a-977d-11e6-9497-96deb570e34d.png">

See attached screenshots, there are some random icons...

**Comment by marisid** [comment]
Fixed by pull request #72.
