### ISSUE TITLE
Line spacing error on profiles.

### ISSUE THREAD

**Issue by RhodesPeter** [GlobeTownDevs/blog#68]
The text in your profiles section is squashed together, I believe this is coming from the `line-height: .75em` line in your css. Here is a screen shot to show the issue.

![screen shot 2016-10-21 at 10 57 46](https://cloud.githubusercontent.com/assets/18164707/19594547/65d10418-977d-11e6-9162-d064df1f9aae.png)

**Comment by marisid** [comment]
Fixed by pull request #72.
